# Generated by Django 5.0 on 2024-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='isFraud',
            field=models.BooleanField(null=True),
        ),
    ]
