# Generated by Django 5.0 on 2024-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0002_alter_transaction_isfraud'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nameDest',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nameOrig',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='isFraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
