# Generated by Django 5.0 on 2024-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0003_transaction_namedest_transaction_nameorig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nameDest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nameOrig',
            field=models.CharField(max_length=255),
        ),
    ]
