# Generated by Django 5.0 on 2024-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0007_alter_transaction_isfraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='isFraud',
            field=models.BooleanField(default=False),
        ),
    ]
